volumes:
  minio_data:
  redis_data:

services:

  # minio:
  #   image: quay.io/minio/minio:RELEASE.2023-03-24T21-41-23Z
  #   restart: always
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=minio123
  #     - minio_data:/data
  #   volumes:
  #   command: 
  #     - server
  #     - /data
  #     - --console-address
  #     - ":9001"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    profiles:
      - redis
    volumes: 
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
    ports:
      - 8081:8081
    profiles:
      - redis

  frps:
    image: ghcr.io/fatedier/frps:v0.61.1
    container_name: frps
    ports:
      - 7500:7500
    volumes:
      - ./frps.yaml:/etc/frp/frps.yaml
    network_mode: host
    restart: always
    command: ["-c", "/etc/frp/frps.yaml"]

  frpc:
    image: ghcr.io/fatedier/frpc:v0.61.1
    container_name: frpc
    environment:
      USER: testuser
    ports:
      - 7400:7400
    depends_on:
      - frps
    volumes:
      - ./frpc.yaml:/etc/frp/frpc.yaml
    network_mode: host
    restart: always
    command: ["-c", "/etc/frp/frpc.yaml"]
